# Generated by Django 3.0.6 on 2020-09-09 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
     
    ]
