# Generated by Django 3.0.6 on 2020-09-09 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen_logo', models.ImageField(upload_to='logo_empresa')),
                ('contacto', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('direccion', models.TextField()),
                ('latitude_empresa', models.FloatField(blank=True, default=0.0, null=True)),
                ('longitude_empresa', models.FloatField(blank=True, default=0.0, null=True)),
                ('descripcion', models.TextField(verbose_name='descripcion_empresa')),
                ('chat_telegram', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Redes_sociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('url_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('groupid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inventario', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_producto', models.ImageField(upload_to='imagen_producto')),
                ('nombre_producto', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True)),
                ('existencia', models.IntegerField(blank=True, default=0, null=True)),
                ('precio', models.FloatField(blank=True, default=0, null=True)),
                ('porcentaje_descuento', models.IntegerField(blank=True, default=0, null=True)),
                ('esta_descuento', models.BooleanField(default=False)),
                ('nuevo_producto', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.Categoria')),
                ('tipo_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.TipoInventario')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.Tipo_producto')),
            ],
        ),
    ]
