# Generated by Django 3.0.6 on 2020-09-28 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_app', '0002_auto_20200910_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_marca_modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tipo_producto',
            new_name='TipoProducto',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='descripcion_categoria',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='cabtidad',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='chat_telegram',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='existencia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_inventario',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.CharField(max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.Producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='marca_modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.MarcaModelo'),
            preserve_default=False,
        ),
    ]
