# Generated by Django 2.1.5 on 2020-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_auto_20201122_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
