# Generated by Django 3.1.1 on 2020-09-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_auto_20200910_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cabtidad',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='chat_telegram',
        ),
    ]
