# Generated by Django 3.0.6 on 2020-09-28 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_auto_20200928_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcamodelo',
            name='descripcion_marca_modelo',
        ),
        migrations.AddField(
            model_name='marcamodelo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marcamodelo',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.Modelo'),
            preserve_default=False,
        ),
    ]
