# Generated by Django 2.1.5 on 2020-12-05 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_auto_20201205_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_compra',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
