# Generated by Django 3.1 on 2020-12-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_orden_fecha_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Media/imagen_cliente/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen_logo',
            field=models.ImageField(upload_to='Media/logo_empresa/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(upload_to='Media/productos_empresa/'),
        ),
    ]
