# Generated by Django 2.1.5 on 2020-12-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_orden_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
