# Generated by Django 3.1 on 2020-12-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_auto_20201207_1910'),
        ('ecommerce_app', '0005_detalleorden_descuento'),
    ]

    operations = [
    ]
