# Generated by Django 2.1.5 on 2020-10-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_auto_20200929_2108'),
        ('ecommerce_app', '0005_auto_20200928_0114'),
    ]

    operations = [
    ]
